[package]
name = "xeqy"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.10.2"
rand = "0.8.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
